version: "3.6"

services:
  sim-global:
    image: chalmersrevere/opendlv-sim-global-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-global --cid=111 --freq=50 --frame-id=0 --x=0.538 --y=1.600 --yaw=3.2 --timemod=0.2"
    # command: "/usr/bin/opendlv-sim-global --cid=111 --freq=50 --frame-id=0 --x=-1.0 --y=0.0 --yaw=0.0 --timemod=0.2"

  sim-motor-kiwi:
    image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-motor-kiwi --cid=111 --freq=200 --frame-id=0 --timemod=0.2"

  sim-camera:
    container_name: sim-camera
    image: chalmersrevere/opendlv-sim-camera-nvidia:v0.0.1
    ipc: "host"
    network_mode: "host"
    volumes:
      - ./conetrack:/opt/map
      # - ./crossing:/opt/map
      - /tmp:/tmp
    environment:
      - DISPLAY=${DISPLAY}
    command: "--cid=111 --frame-id=0 --map-path=/opt/map --x=0.0 --z=0.095 --width=1280 --height=720 --fovy=48.8 --freq=7.5 --timemod=0.1 --verbose"
