version: '2'

services:
  cone-detection:
    image: registry.git.chalmers.se/courses/tme290/2020/group8/opendlv-perception-cone-detection:v1.7
    restart: on-failure
    network_mode: "host"
    ipc: "host"
    volumes:
        - /tmp:/tmp
    environment:
        - DISPLAY=${DISPLAY}
    command: "--cid=111 --name=video0.argb --width=1280 --height=720"

  kiwi-detection:
    image: registry.git.chalmers.se/courses/tme290/2020/group8/opendlv-perception-kiwi-detection:v1.3.2
    restart: on-failure
    network_mode: "host"
    ipc: "host"
    volumes:
        - /tmp:/tmp
    environment:
        - DISPLAY=${DISPLAY}
    command: "--cid=111 --name=video0.argb --width=1280 --height=720 --weights=simulation"

